### ISSUE TITLE
Create an abstract service for accessing KnownEntities

### ISSUE THREAD

**Issue by briedinger** [arwatts16/Search-Extension#4]
Our first implementation will be UOM, file-based.  We'll later plugin UOM-server based.  UOM in this context will represent the generic concept of "things we know about".  Create a service, interfaces and such, which will allow us to generically query known entities.

There should be a manager class/prototype.   The manager should have specific implementations (file, server, etc) register with it.  The client calls the manager and asks for known things.  The manager uses it's registered implementation, makes the appropriate call, and returns the results.

Also, define the model.  The manager should return results using a standard model object.

**Comment by csgibson** [comment]
@briedinger I think this may be OBE now?
