### ISSUE TITLE
save_load.js needs to alert content.js when the variables have been updated 

### ISSUE THREAD

**Issue by arwatts16** [arwatts16/Search-Extension#7]
Once the user had saved new values into the local storage, it needs to alert the content script that there has been a change, and send it the updated values.

**Comment by arwatts16** [comment]
the existing code already did that so now I'm making it so that is sends over the necessary information (active and input keywords)

**Comment by csgibson** [comment]
@arwatts16 there may be better ways to do this than the local storage solution.
